[workspace]
members = [
    "crates/faceauth-camera",
    "crates/faceauth-cli",
    "crates/faceauth-core",
    "crates/faceauth-daemon",
    "crates/faceauth-model",
    "crates/faceauth-protocol",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.92"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Tinnci/faceauth-rs"

[workspace.dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.54", features = ["derive"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
sha2 = "0.11.0"
spdx = "0.13.4"
thiserror = "2.0.17"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter", "fmt"] }
udev = "0.9.3"
uuid = { version = "1.19.0", features = ["serde", "v4"] }

[workspace.lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
expect_used = "deny"
panic = "deny"
unwrap_used = "deny"
