[package]
name = "faceauth-management-dbus"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
faceauth-authz = { path = "../faceauth-authz", version = "0.1.0" }
faceauth-management = { path = "../faceauth-management", version = "0.1.0" }
futures-channel = "0.3.31"
futures-util = { version = "0.3.31", default-features = false }
serde.workspace = true
zbus.workspace = true

[dev-dependencies]
faceauth-protocol = { path = "../faceauth-protocol", version = "0.1.0" }
faceauth-transport = { path = "../faceauth-transport", version = "0.1.0" }
futures-lite = "2.6.1"

[lints]
workspace = true
