[package]
name = "faceauth-inference"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
faceauth-model = { path = "../faceauth-model", version = "0.1.0" }
ort.workspace = true
thiserror.workspace = true
zeroize.workspace = true

[lints]
workspace = true
