[package]
name = "faceauth-liveness"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
faceauth-core = { path = "../faceauth-core", version = "0.1.0" }
getrandom.workspace = true
serde.workspace = true
thiserror.workspace = true

[lints]
workspace = true
