[package]
name = "faceauth-management"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
faceauth-authz = { path = "../faceauth-authz", version = "0.1.0" }
faceauth-protocol = { path = "../faceauth-protocol", version = "0.1.0" }
serde.workspace = true
thiserror.workspace = true
uuid.workspace = true

[dev-dependencies]
faceauth-transport = { path = "../faceauth-transport", version = "0.1.0" }

[lints]
workspace = true
